CREATE TABLE IF NOT EXISTS facebook_ads_raw (
  date date,
  campaign_id text,
  campaign_name text,
  ad_set_id text,
  ad_set_name text,
  impressions bigint,
  clicks bigint,
  spend numeric,
  conversions bigint,
  video_views bigint,
  engagement_rate numeric,
  reach bigint,
  frequency numeric
);

CREATE TABLE IF NOT EXISTS google_ads_raw (
  date date,
  campaign_id text,
  campaign_name text,
  ad_group_id text,
  ad_group_name text,
  impressions bigint,
  clicks bigint,
  cost numeric,
  conversions bigint,
  conversion_value numeric,
  ctr numeric,
  avg_cpc numeric,
  quality_score int,
  search_impression_share numeric
);

CREATE TABLE IF NOT EXISTS tiktok_ads_raw (
  date date,
  campaign_id text,
  campaign_name text,
  adgroup_id text,
  adgroup_name text,
  impressions bigint,
  clicks bigint,
  cost numeric,
  conversions bigint,
  video_views bigint,
  video_watch_25 bigint,
  video_watch_50 bigint,
  video_watch_75 bigint,
  video_watch_100 bigint,
  likes bigint,
  shares bigint,
  comments bigint
);

CREATE TABLE IF NOT EXISTS unified_ads (
  date date,
  platform text,
  campaign_id text,
  campaign_name text,
  ad_group_id text,
  ad_group_name text,
  impressions bigint,
  clicks bigint,
  spend numeric,
  conversions bigint,
  conversion_value numeric,
  video_views bigint,
  reach bigint,
  frequency numeric,
  engagement_rate numeric,
  likes bigint,
  shares bigint,
  comments bigint,
  video_watch_25 bigint,
  video_watch_50 bigint,
  video_watch_75 bigint,
  video_watch_100 bigint,
  ctr numeric,
  avg_cpc numeric,
  quality_score int,
  search_impression_share numeric
);

TRUNCATE TABLE unified_ads;

INSERT INTO unified_ads (
  date,
  platform,
  campaign_id,
  campaign_name,
  ad_group_id,
  ad_group_name,
  impressions,
  clicks,
  spend,
  conversions,
  conversion_value,
  video_views,
  reach,
  frequency,
  engagement_rate,
  likes,
  shares,
  comments,
  video_watch_25,
  video_watch_50,
  video_watch_75,
  video_watch_100,
  ctr,
  avg_cpc,
  quality_score,
  search_impression_share
)
SELECT
  f.date,
  'facebook' AS platform,
  f.campaign_id,
  f.campaign_name,
  f.ad_set_id AS ad_group_id,
  f.ad_set_name AS ad_group_name,
  f.impressions,
  f.clicks,
  f.spend,
  f.conversions,
  CAST(NULL AS numeric) AS conversion_value,
  f.video_views,
  f.reach,
  f.frequency,
  f.engagement_rate,
  CAST(NULL AS bigint) AS likes,
  CAST(NULL AS bigint) AS shares,
  CAST(NULL AS bigint) AS comments,
  CAST(NULL AS bigint) AS video_watch_25,
  CAST(NULL AS bigint) AS video_watch_50,
  CAST(NULL AS bigint) AS video_watch_75,
  CAST(NULL AS bigint) AS video_watch_100,
  CAST(NULL AS numeric) AS ctr,
  CAST(NULL AS numeric) AS avg_cpc,
  CAST(NULL AS int) AS quality_score,
  CAST(NULL AS numeric) AS search_impression_share
FROM facebook_ads_raw f
UNION ALL
SELECT
  g.date,
  'google' AS platform,
  g.campaign_id,
  g.campaign_name,
  g.ad_group_id,
  g.ad_group_name,
  g.impressions,
  g.clicks,
  g.cost AS spend,
  g.conversions,
  g.conversion_value,
  CAST(NULL AS bigint) AS video_views,
  CAST(NULL AS bigint) AS reach,
  CAST(NULL AS numeric) AS frequency,
  CAST(NULL AS numeric) AS engagement_rate,
  CAST(NULL AS bigint) AS likes,
  CAST(NULL AS bigint) AS shares,
  CAST(NULL AS bigint) AS comments,
  CAST(NULL AS bigint) AS video_watch_25,
  CAST(NULL AS bigint) AS video_watch_50,
  CAST(NULL AS bigint) AS video_watch_75,
  CAST(NULL AS bigint) AS video_watch_100,
  g.ctr,
  g.avg_cpc,
  g.quality_score,
  g.search_impression_share
FROM google_ads_raw g
UNION ALL
SELECT
  t.date,
  'tiktok' AS platform,
  t.campaign_id,
  t.campaign_name,
  t.adgroup_id AS ad_group_id,
  t.adgroup_name AS ad_group_name,
  t.impressions,
  t.clicks,
  t.cost AS spend,
  t.conversions,
  CAST(NULL AS numeric) AS conversion_value,
  t.video_views,
  CAST(NULL AS bigint) AS reach,
  CAST(NULL AS numeric) AS frequency,
  CAST(NULL AS numeric) AS engagement_rate,
  t.likes,
  t.shares,
  t.comments,
  t.video_watch_25,
  t.video_watch_50,
  t.video_watch_75,
  t.video_watch_100,
  CAST(NULL AS numeric) AS ctr,
  CAST(NULL AS numeric) AS avg_cpc,
  CAST(NULL AS int) AS quality_score,
  CAST(NULL AS numeric) AS search_impression_share
FROM tiktok_ads_raw t;

